name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation
  core_ui:
    path: ../core_ui

  get_it: ^8.0.2
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

