name: settings_page
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  navigation:
    path: ../../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0

flutter:


