name: core_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  cached_network_image: ^3.4.1
  animated_text_kit: ^4.2.2

  core:
    path: ../core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


